apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: DevOps-MathOperations
  template:
    metadata:
      labels:
        app: DevOps-MathOperations
    spec:
      containers:
      - name: calc
        image: nikim1/devops-mathoperations:latest
        ports:
        - containerPort: 5000
